import Head from 'next/head'
import Image from 'next/image'
import Default from '../layout/default'

export default function Home() {
  return (
    <>
      <Head>
        <title>SIGT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/navbaricon/logo-lomas.svg" />
      </Head>
      <Default>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </Default>
    </>
  )
}
